### ISSUE TITLE
Issue when deploying to sandbox via mdapi 

### ISSUE THREAD

**Issue by jonnyr** [muenzpraeger/salesforce-einstein-object-detection-mobile-example#2]
I’ve installed the Einstein platform services wrapper successfully to a sandbox and then cloned and converted this repo via mdapi to push to the same sandbox. On deployment, I’m getting the following errors: 

Component Errors
ShelfScanner	Lightning Component Bundle	0	0	Invalid definition for null:ShelfScanner: null
ShelfScanner	Lightning Component Bundle	0	0	Invalid definition for null:ShelfScanner: null
ShelfScanner	Apex Class	19	86	Method does not exist or incorrect signature: [Object].toString()

![a1615ad2-bd8b-49eb-9c98-510f0e70bfe4](https://user-images.githubusercontent.com/1402057/35339553-e31e6a42-00ee-11e8-9de6-789ab05b2131.jpeg)

Any ideas? Thanks for the fantastic tool - we are really excited to try this out!

**Comment by jonnyr** [comment]
I was able to get this deployed into our sandbox by creating the ShelfScanner component directly in the sandbox and then I changed line 19 to the following: 

From:
 `Scan_Result__c storeResult = new Scan_Result__c(Name=result.get('label').toString(), Count__c=(Decimal)result.get('count'), Shelf_Scan__c=scan.Id);` 

To: 
`Scan_Result__c storeResult = new Scan_Result__c(Name=String.valueOf(result.get('label')), Count__c=(Decimal)result.get('count'), Shelf_Scan__c=scan.Id);`

**Comment by muenzpraeger** [comment]
Thanks @jonnyr - it's fixed now in the master branch.

**Comment by jonnyr** [comment]
Sweet - thanks for the quick reply and merge @muenzpraeger!
